chef of day

diff --git a/.github/workflows/recipe-chef-of-the-day.yml b/.github/workflows/recipe-chef-of-the-day.yml
--- a/.github/workflows/recipe-chef-of-the-day.yml
+++ b/.github/workflows/recipe-chef-of-the-day.yml
@@ -1,7 +1,7 @@
 # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
 
-name: Set Recipe/Chef of the day
+name: Set Recipe & Chef of the day
 
 on:
   schedule:
@@ -11,34 +11,25 @@ on:
 jobs:
 
   set-stuff-of-the-day:
-
-    name: Test
+    name: Hit API
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout project
-        uses: actions/checkout@v4
 
-      - name: Setup PHP Action
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: '7.4'
-          extensions: mysqli, http, json
-          tools: composer
-        id: php
+      - name: Install JQ
+        run: sudo apt-get install -y jq
 
-      - name: Write env file
+      - name: Hit API Endpoint
         run: |
-          touch .env
-          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
-          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
-          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
-          echo "MAIL_HOST=MAIL_HOST" >> .env
-          echo "MAIL_USERNAME=MAIL_USERNAME" >> .env
-          echo "MAIL_PASSWORD=MAIL_PASSWORD" >> .env
-          echo "PRODUCTION=1" >> .env
-
-      - name: Install dependencies
-        run: composer install
-
-      - name: Run
-        run: php automation/set-recipe-chef-of-the-day.php
+          curl -X POST -s --write-out '%{http_code}' -o '/tmp/output.txt' --url ${{ secrets.PROJECT_DOMAIN }}/api/v1/system/ops/set-recipe-chef-of-the-day.php
+          #cat /tmp/output.txt
+          MESSAGE=$(echo $(cat /tmp/output.txt) | jq -r '.message')
+          CODE=$(echo $(cat /tmp/output.txt) | jq -r '.response_code')
+          echo $MESSAGE
+          
+          if [ $CODE != "200" ]; then
+            echo "FAILURE";
+            exit 1;
+          else
+            echo "SUCCESS";
+          fi
